### Get all cateogries
GET {{base_url}}/categorias
###

### Get Products by category
GET {{base_url}}/categorias/662764f4-5290-4bf9-bf84-48b7bc033830
###

### Create a new category
POST {{base_url}}/categorias
Content-Type: application/json

{
    "name": "Category 1",
    "color": "#000000"
}
###

### Update a category
PUT {{base_url}}/categorias/662764f4-5290-4bf9-bf84-48b7bc033830
Content-Type: application/json

{
    "color": "#FFFFFF"
}
###

### Delete a category
DELETE {{base_url}}/categorias/662764f4-5290-4bf9-bf84-48b7bc033830
###