### Get all videos
GET {{base_url}}/videos


### Get a video
GET {{base_url}}/videos/764b94a1-5925-43b9-a818-7f1562d03857

### Create a video
POST {{base_url}}/videos
Content-Type: application/json

{
    "title": "My video novo",
    "description": "My new video description",
    "url": "https://www.youtube.com/watch?v=9bZkp7q19f0"
}

### Update a video
PUT {{base_url}}/videos/764b94a1-5925-43b9-a818-7f1562d03857
Content-Type: application/json

{
    "title": "My video updated"
}

### Delete a video
DELETE {{base_url}}/videos/56314e62-d481-4acf-9652-b9b7462b25f3
